### ISSUE TITLE
Vector of StaticArrays inside ArrayPartition

### ISSUE THREAD

**Issue by Gregstrq** [SciML/RecursiveArrayTools.jl#125]
I have tried to use a `Vector` of `StaticArray`s inside an `ArrayPartition`. This led to a non-trivial problem with DifferentialEquations.jl, when I tried to use such an `ArrayPartition` as the state vector for an ODE: the resulting element type of `ArrayPartition` happened to be `Any` and it broke `recursive_unitless_bottom_eltype` function which is used somewhere inside DifferentialEquations.jl.

In order to illustrate this, consider the following example:
```
using RecursiveArrayTools, StaticArrays

a = ArrayPartition((zeros(Float64, 10), zeros(SVector{3,Float64}, 10)))
```
The output of `typeof(a)` is
> ArrayPartition{Any,Tuple{Array{Float64,1},Array{SArray{Tuple{3},Float64,1,3},1}}}

And if you try to do `recursive_unitless_bottom_eltype(a)`, you get a never-ending recursion:
>ERROR: StackOverflowError:
Stacktrace:
 [1] recursive_unitless_bottom_eltype(::Type{Any}) at ~/.julia/packages/RecursiveArrayTools/BVS4M/src/utils.jl:86 (repeats 79984 times)

In the example I provided, it would be logical if the element type of `ArrayPartition` is `Float64`. It seems that we can get such behaviour if we slightly change the constructor for `ArrayPartition`:
```
function ArrayPartition(x::S, ::Type{Val{copy_x}}=Val{false}) where {S<:Tuple,copy_x}
  T = promote_type(recursive_bottom_eltype.(x)...)
  if copy_x
    return ArrayPartition{T,S}(copy.(x))
  else
    return ArrayPartition{T,S}(x)
  end
end
```
The only change I propose to make is to replace `eltype` with `recursive_bottom_eltype` in the type promotion. Potentially, this solution can deal with any kind of crazy nesting of arrays.

**Comment by ChrisRackauckas** [comment]
Yes I think type promotion is probably the right thing to do there.

**Comment by ChrisRackauckas** [comment]
Could you make a PR?

**Comment by Gregstrq** [comment]
I sort of made it: https://github.com/SciML/RecursiveArrayTools.jl/pull/126.
However, it seems I messed up the syntax for linking the issue. I named the pull request "Fixes #125", where 125 is the number of this issue, but it hasn't automatically linked.

May be I drop the pull request and do that again, if you tell me the correct way to link it to this issue.

**Comment by Gregstrq** [comment]
I can add the very example I used here as a test.
I have a noob question: how do I modify an existing PR?

**Comment by Gregstrq** [comment]
Ok, It seems I just need to push the changes to the branch which I use for PR.
