### ISSUE TITLE
names / labels for the arrays in a Vector of Arrays?

### ISSUE THREAD

**Issue by ym-han** [SciML/RecursiveArrayTools.jl#133]
This is super minor, but: is there a way to use names or labels for the arrays in a Vector of Arrays (so that we can do, e.g., `push!(test[label], 123)`?

**Comment by ChrisRackauckas** [comment]
Are you looking for https://github.com/jonniedie/ComponentArrays.jl?

**Comment by ym-han** [comment]
Thanks, that's a really cool package! (And also now that I think more about it, an ordinary named tuple might be enough for my use case. Oops!)
