### ISSUE TITLE
Calling similar on ArrayPartition does not respect the dims argument

### ISSUE THREAD

**Issue by garibarba** [SciML/RecursiveArrayTools.jl#135]
Usage of `similar` in e.g.:
https://github.com/JuliaDiff/ForwardDiff.jl/blob/909976d719fdbd5fec91a159c6e2d808c45a770f/src/jacobian.jl#L149
is broken because it returns an `ArrayPartition` with the wrong number of elements.
This breaks later calls to e.g. `reshape` (see https://github.com/SciML/DiffEqSensitivity.jl/issues/404).

The returned array has the same size as the source `ArrayPartition`, and not the expected number of elements described by the `dims` argument(s).

This affects these two definitions:
https://github.com/SciML/RecursiveArrayTools.jl/blob/734999e278ab5a6f9197669df155341d284b26fd/src/array_partition.jl#L22-L23
https://github.com/SciML/RecursiveArrayTools.jl/blob/734999e278ab5a6f9197669df155341d284b26fd/src/array_partition.jl#L31-L32

**Comment by garibarba** [comment]
Some ideas:

1. `Base.similar(A::ArrayPartition, dims::NTuple{N,Int}) where {N} = similar(A.x[1], dims)`, as long as the types of all in `A.x` are the same.
2.   If `prod(dims)` is a multiple (factor  `n`) of the `length` of the `A::ArrayPartition`, return an ArrayPartition of `n` ArrayPartitions.

**Comment by ChrisRackauckas** [comment]
I think that can work. In the ragged case just error?

**Comment by agerlach** [comment]
This shows up in `Zygote.jacobian` too and causes issues w/ _gradcopy!
https://github.com/FluxML/Zygote.jl/blob/4e54eb79de85a47d64776b61a1a225ccdd133fc0/src/lib/grad.jl#L142

**Comment by garibarba** [comment]
I've tried 1. and 2. on a toy `SteadyStateProblem` and they seem to work fine. But my larger problem is crashing in a `Zygote` call so I'm trying to figure that out before doing a a pull request, although it seems unrelated on first sight.
