### ISSUE TITLE
ArrayPartition broadcasting change downstream regressions

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/RecursiveArrayTools.jl#137]
https://github.com/SciML/RecursiveArrayTools.jl/pull/136 seems to have caused downstream test failures.

https://github.com/SciML/OrdinaryDiffEq.jl/pull/1371/checks?check_run_id=2363261434#step:6:1070

It may need to get reverted unless we can figure out how to fix this.

**Comment by ChrisRackauckas** [comment]
@jdeldre for reference. I'll try and find a nice MWE.

**Comment by jdeldre** [comment]
I think I see the root of the problem. It has to do with `Array{Float64, 0}`, which now get made into `Float64` with broadcasting. This should be fixable.
