### ISSUE TITLE
Specialized method to `map` over an `ArrayPartition`?

### ISSUE THREAD

**Issue by jonniedie** [SciML/RecursiveArrayTools.jl#140]
`map` over an `ArrayPartition` is slower than mapping over the inner partitions and reconstructing an `ArrayPartition`. I typically use something like:

```julia
partition_map(f, array::ArrayPartition) = ArrayPartition(map(partition -> map(f, partition), array.x))
partition_map(f, array) = map(f, array)
```

Would it be worth making this the default for `map` over a single `ArrayPartition`?

**Comment by ChrisRackauckas** [comment]
Yes, that would be a good default.
