### ISSUE TITLE
2.13-> 2.14: broken API or breaking change ?

### ISSUE THREAD

**Issue by j-fu** [SciML/RecursiveArrayTools.jl#146]
Between 2.13 and 2.14, the meaning of  `a[i,:,t]` changed.  I think it is broken. If it is intended to be a breaking change I would expect the version to be 3.0 ...

- [mwe](https://gist.github.com/j-fu/b2bf4ae92f5619199ca51865d12c234f#file-mwe-jl)

- output  of [2.13.0](https://gist.github.com/j-fu/b2bf4ae92f5619199ca51865d12c234f#file-out_2-13)

- output  of [2.14.0](https://gist.github.com/j-fu/b2bf4ae92f5619199ca51865d12c234f#file-out_2-14)

**Comment by ChrisRackauckas** [comment]
That wasn't intended. @sharanry can you take a quick look at this? This might be the reason for some downstream breakage.

**Comment by sharanry** [comment]
I am looking into it.
