### ISSUE TITLE
Behaviour of recursive_unitless_bottom_eltype on Vector{Real}

### ISSUE THREAD

**Issue by leoluecken** [SciML/RecursiveArrayTools.jl#380]
Currently,
```julia
recursive_unitless_bottom_eltype(Vector{Real})
```
 gives 
```julia
Int64
```
Ultimately, this is because this call recurses to
```julia
function recursive_unitless_bottom_eltype(a::Type{T}) where {T <: Number}
    eltype(a) == Number ? Float64 : typeof(one(eltype(a)))
end
```
and `one(Real) === 1`

I'd suggest to replace `eltype(a) == Number ?` by `eltype(a) in [Number, Real] ?` if nothing speaks against it...

**Comment by ChrisRackauckas** [comment]
How did you actually hit this? I think we normally just throw a higher level error in the solvers because if you have a Vector{Real} then things are already bad 😅

**Comment by leoluecken** [comment]
Well, originally I was trying to set up a continuation for periodic orbits in a rather ugly system using BifurcationKit. It was using Float64-Vectors for its state, which did not work. I did not understand the specifics, but it had to do with the fact that the ForwardDiff.Dual class is not a subclass of Float64. Since it *is* a subclass of Real, I changed the code to use Vector{Real} instead of Vector{Float64}. This is how this situation came up. :grim

**Comment by leoluecken** [comment]
I start to understand, why you say things get bad with Vector{Real}... The next problem occurs in OrdinaryDiffEq at `ode_determine_initdt()`, because 
```julia
u₁ = zero(u0) # required by DEDataArray
```
results in a zero-vector of type `Int64` if `u0` is a `Vector{Real}` 

Would you by chance have any suggestion, how the original problem with ForwardDiff.Dual could be solved without Vector{Real}?? 

I wondered whether this could be avoided by turning automatic differentiation off, but I couldn't figure out, how. And I'm not even sure, whether this is really causing this.

**Comment by ChrisRackauckas** [comment]
You don't need the Vector{Real} for this. Just make it a Vector{T} where `T` matches the type being differentiated. How are you defining this array?

**Comment by ChrisRackauckas** [comment]
```julia
mutable struct State{T, T2, T3}
    # time in days
    t::T
    # phytoplankton [10^6 cells / ml]
    P::Vector{T2}
    # heterotrophs [10^6 cells / ml]
    H::Vector{T3}
    # ... etc
end
```

Just let it be parametric.

**Comment by leoluecken** [comment]
I think I got it working now!

I only used a single type, though

```julia
mutable struct State{T}
    # time in days
    t::T
    # phytoplankton [10^6 cells / ml]
    P::Vector{T}
    # heterotrophs [10^6 cells / ml]
    H::Vector{T}
    # ... etc
end
```

Is there a reason, why one should use different types?

**Comment by ChrisRackauckas** [comment]
Depends on if they are all the same or different

**Comment by leoluecken** [comment]
Ok, they all where Float64 - so one T seems fine. Thanks a lot for taking time to look at this! :pray:
