### ISSUE TITLE
New release to support FastBroadcast 0.3 in the SciML ecosystem?

### ISSUE THREAD

**Issue by chriselrod** [SciML/RecursiveArrayTools.jl#381]
Currently, FastBroadcast 0.3 cannot be installed alongside SciMLBase, DiffEqBase, or OrdinaryDiffEq.

Yet these package's `Project.toml`'s already allow for 0.3. Ideally, we'd have gotten a RecursiveArrayTools release first to be able to properly test before merging compat updates.

But it'd also be nice to make those compat updates real by no longer having `RecursiveArrayTools` block them.

**Comment by ChrisRackauckas** [comment]
Done
