### ISSUE TITLE
Efficient broadcast overloads for AbstractVectorOfArray

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/RecursiveArrayTools.jl#5]
It can broadcast along the linear index. This will make its broadcast performant for most analyses, and so the only indexing performance issue could be from directly using the matrix indexing.

**Comment by ChrisRackauckas** [comment]
the fallbacks using Cartesians actually do super well. I don't think overloads are needed for speed. It is annoying that it returns a standard `Vector{Array}` though.

**Comment by ChrisRackauckas** [comment]
@ScottPJones I know you've been looking at this stuff: do you know how you can add something to say "make it return a VectorOfArray"?

**Comment by ScottPJones** [comment]
I wish I did, that's the same problem that I've been running into with trying to get the broadcasting of MultiScaleArrays to work, if you don't add specializations for broadcast!, broadcast, it just returns `Vector{T}`
