### ISSUE TITLE
mean(x::VectorOfArrays, dims=i) off by factor of size(x,1)

### ISSUE THREAD

**Issue by yha** [SciML/RecursiveArrayTools.jl#53]
```
julia> using RecursiveArrayTools
julia> using Statistics
julia> x = VectorOfArray([[i+j for i=j:j+2] for j=1:2])
2-element Array{Array{Int64,1},1}:
 [2, 3, 4]
 [4, 5, 6]

julia> mean(x,dims=1), mean(Array(x),dims=1)
([9.0 15.0], [3.0 5.0])

julia> mean(x,dims=2), mean(Array(x),dims=2)
([9.0; 12.0; 15.0], [3.0; 4.0; 5.0])
```

**Comment by ChrisRackauckas** [comment]
I'm not sure what `mean(x,dims=2)` is supposed to mean on a VectorOfArray since it iterates over arrays and not values? It only has one dimension?

**Comment by yha** [comment]
`VectorOfArray` seems to behave as a two-dimensional array in other contexts, e.g. `size` returns two elements, you can transpose it etc., and I expected it to behave as two-dimensional here. It works for `sum` (same `x` as previous example):
```
julia> sum(x,dims=1)
1×2 Array{Int64,2}:
 9  15
julia> sum(x,dims=2)
3×1 Array{Int64,2}:
  6
  8
 10
```
Admittedly, `sum(x)` seems to treat it as a one-dimensional array of vectors, where I expected it to be the same as `sum(Array(x))`, so perhaps I'm misunderstanding the intended behavior.
In any case, the current behavior of `mean` doesn't make sense in if it's interpreted as one-dimensional. The result has the correct size for the two-dimensional interpretation but the wrong values, so it can be quite a pitfall.

**Comment by ChrisRackauckas** [comment]
Yeah, I've wondered if we should get rid of the one-dimensional iterating for awhile, but that would be very breaking for DifferentialEquations.jl, so I'd want an issue and discussion in that repo whether that would be something for DiffEq 7.0

**Comment by ChrisRackauckas** [comment]
Fixed
