### ISSUE TITLE
allocating linearalgebra

### ISSUE THREAD

**Issue by rveltz** [SciML/RecursiveArrayTools.jl#72]
Hi,

I am surprised by the following behavior. Can you please tell me if this is expected?

Thank you,

Best regards,

```
using BenchmarkTools

xce0 = ArrayPartition(zeros(2),[0.])
xcde0 = copy(xce0)

function foo(y, x)
	y .= y .+ 2 .* x
end

@btime foo($xcde0, $xce0)
```
which gives

```
julia> @btime foo($xcde0, $xce0)
  30.138 ns (3 allocations: 48 bytes)
```

**Comment by ChrisRackauckas** [comment]
It's 48 bytes, so it could just be the fact that you're returning it. What happens if you add nothing to the end?

**Comment by rveltz** [comment]
Nothing :(

What's more:

```
function foo(y, x)
	y .= y .+ 2 .* x + 3 .* x
	nothing
end

@btime foo($xcde0, $xce0)
```
gives `243.377 ns (19 allocations: 832 bytes)`

**Comment by ChrisRackauckas** [comment]
Uhh, can't say I have an explanation for that. I wonder if there's something in the broadcast definition we should be avoiding. Whatever it is, this will take time.
