### ISSUE TITLE
Initialisation of an empty VectorOfArrays

### ISSUE THREAD

**Issue by SteffenPL** [SciML/RecursiveArrayTools.jl#77]
It was difficult for me to figure out how to construct an empty VectorOfArrays.
Maybe the documentation here could be improved? (Or I am not experiences enough...)

This line constructs an empty array of arrays
`a_empty = Array{Array{Float64,1}}([])`
but the following line crashes
`vv = VectorOfArray( a_empty )`
with the error
> ERROR: BoundsError: attempt to access 0-element Array{Array{Float64,N} where N,1} at index [1]
> Stacktrace:
>  [1] getindex at .\array.jl:728 [inlined]
>  [2] VectorOfArray(::Array{Array{Float64,N} where N,1}) at C:\Users\steff\.juliapro\JuliaPro_v1.2.0-1\packages\RecursiveArrayTools\kOAyM\src\vector_of_array.jl:13 [3] top-level scope at none:0

Using the other constructor works, i.e.
`v = VectorOfArray(a_empty , (1,1))`

**Comment by ChrisRackauckas** [comment]
Thanks. The documentation can be improved or, or maybe the implementation. I would've thought what you tried would work, but 🤷‍♂ yeah it needs the size... this can probably get a good workaround.

**Comment by mforets** [comment]
If all the elements of the outer vector are of the same type (which is the assumption in the [fallback constructor](https://github.com/SciML/RecursiveArrayTools.jl/blob/master/src/vector_of_array.jl#L19)) one can add a more specific constructor:

```julia
function VectorOfArray(vec::AbstractVector{VT}) where {T, N, VT<:AbstractArray{T, N}}
    return VectorOfArray{T, N+1, typeof(vec)}(vec)
end
```
This covers the empty case in the OP,

```julia
julia> Array{Vector{Float64}}([]) |> VectorOfArray
0-element Array{Array{Float64,1},1}
```

**Comment by ChrisRackauckas** [comment]
Awesome, that's a good idea. Could we get a quick PR?
